// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozcsaisabbmouqywpqqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96Y3NhaXNhYmJtb3VxeXdwcXFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDk3NDUsImV4cCI6MjA3MzI4NTc0NX0.AswhCZrZLHFT8S3UMuqYBsgla40JGMwtu2zDHxQEIls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});